Madeleine google analytics
nens/lizard-docs pull request #64
Opened 2022-12-15 15:59 UTC by GeOdin

2022-12-15 16:01 UTC, GeOdin commented
Note: something similar has been done for thre threedi-docs
https://github.com/nens/threedi-docs/blob/master/source/conf.py

2022-12-16 11:00 UTC, lexvand commented
I think @reinout is a better reviewer for this PR.

2022-12-16 12:56 UTC, reinout commented
Qua code klopt het allemaal wel. De vraag is even of het google ID klopt, dat kan ik niet zien.

Maar... **gil, krijs, alarm**. Google analytics? Ik vind het raar dat mijn naam er ergens bij staat in de "git blame" van de 3di docs. Want: ik dacht dat we google analytics niet meer gebruikten. Ok, misschien bij de www.nelen-schuurmans.nl, maar niet bij de documentatie enzo.

Want: we hebben geen "vind u cookies goed?" vraag (verplicht, want google zet cookies). En we hebben geen pagina die uitlegt wat er met cookies en dat soort privacy-gevoelige zaken op onze website gebeurd. Dus... door dit toe te voegen zijn we in overtreding. (Of het PR moet uitgebreid worden met de benodigde zaken om het GDPR-compatible te maken).

En ik ga even wat breder alarm slaan :-)

2022-12-16 12:57 UTC, reinout requested changes
Code zelf klopt wel, maar volgens mij mag google analytics niet.

2022-12-19 08:58 UTC, Patrick-Nijman commented
Je kunt google analytics cookieless implementeren:

https://helgeklein.com/blog/google-analytics-cookieless-tracking-without-gdpr-consent/

We hebben het tijdens OPS overleg gehad om over te stappen op Matamo @Wolfensteijn wat is hier de status van en op welke termijn kunnen we dit ook implementeren op de andere sites?

2022-12-19 10:20 UTC, Wolfensteijn commented
Ik heb een Matomo installatie draaien op https://analytics.nelen-schuurmans.nl

De laatste keer dat ik hier mee bezig was liep ik volgens mij tegen wat user issues aan, maar die details zijn wat wazig momemteel.

Deze installatie is verder nog niet in gebruik genomen. De benodigde trackingcode kan zo aangemaakt worden, en door een ik neem aan frontender geïmplementeerd worden in een van onze sites om mee te gaan testen.

Ik denk wel dat het goed is om te kijken of misschien de Matomo cloud ook een optie zou zijn. Een aantal features zitten wel standaard in de cloud, maar kosten geld als je die zelf wilt hosten. 

https://matomo.org/pricing/

2023-01-02 09:59 UTC, GeOdin commented
In dat geval is deze pull request overbodig geworden.
Ik zal hem sluiten.

2023-01-02 09:59 UTC, closed without merging